receive_config:
  topic: ""
  stream_ids:
    - cam1
    - cam2
    - cam3

batch:
  max_batch_size: 8
  max_wait_ms: 5

preprocess:
  workers: 4
  input_size: [640, 640]
  decode:
    enabled: false
    type: ffmpeg

model:
  model_name: yolo11n
  model_path: E:/projects/Ai/TraVis/perception/perception/data/models/yolo11n.pt
  img_size: [640, 640]
  batch_size: 16
  fp16: true